---
title: "Untitled"
author: "Saloua Daouki"
date: "2023-10-21"
output: html_document
---

# Loading libraries:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Introduction:

The goal of this project is to find and use data to answer the question "Which are the most valued data science. Our group members are; Carol Campbell, Kossi Akplaka, Souleymane Doumbia and Saloua Daouki.

# Loading data:

```{r }
url3 <- 'https://raw.githubusercontent.com/Group-Project-Data-607/Project3/main/Data_Science_job.csv'
skills <- read.csv(file = url3)
head(skills)
```

# Tidying the data:

You can also embed plots, for example:

```{r pressure, echo=FALSE}
df_skills <- data.frame(skills)
df_skills
```

```{r subsetting the data}
required_skills <- subset(df_skills, select = c('title', 'company_name', 'location', 'Job.posting.location', 'description', 'schedule_type', 'Required.skills'))
colnames(required_skills)[7] ="skills"
head(required_skills)
```

```{r subsetting the data again to pick only data science jobs}
skills_subset <- subset(required_skills, grepl("data science", required_skills$title, ignore.case = TRUE))
```

```{r extracting hard skills from skills column}
freq_hardskills<- skills_subset %>%
    mutate(R = grepl("\\bR\\b,|ggplot", skills, ignore.case=TRUE)) %>%
    mutate(python = grepl("Python|pandas|numpy", skills, ignore.case=TRUE)) %>%
    mutate(SQL = grepl("SQL|postgresql|mysql|nosql", skills, ignore.case=TRUE)) %>%
    mutate(Microsoft = grepl("excel|word|power point|spreadsheet", skills, ignore.case=TRUE)) %>%
    mutate(Azure = grepl("azur", skills, ignore.case=TRUE)) %>%
    mutate(Power_bi = grepl("power bi", skills, ignore.case=TRUE)) %>%
    mutate(Matplotlib = grepl("matplotlib", skills, ignore.case=TRUE)) %>%
    mutate(Tableau = grepl("tableau", skills, ignore.case=TRUE)) %>%
    mutate(Matlab = grepl("matlab", skills, ignore.case=TRUE)) %>%
    mutate(Java = grepl("java|javascript", skills, ignore.case=TRUE)) %>%
    mutate(gcp = grepl("gcp", skills, ignore.case=TRUE)) %>%
    mutate(cplusplus = grepl("c", skills, ignore.case=TRUE)) %>%
    mutate(Jupyter = grepl("jupyter", skills, ignore.case=TRUE)) %>%
    mutate(Visio = grepl("visio", skills, ignore.case=TRUE)) %>%
    mutate(Git = grepl("git", skills, ignore.case=TRUE)) %>%
    mutate(Other_skills = grepl("spss|sas|ssis|redshift|outlook|crystal|looker|airflow|snowflake|sharepoint|spark|go|hadoop|linus|unix|rust|alteryx|aws|vba|microstrategy", skills, ignore.case=TRUE)) %>%
  select(title, R, python, SQL, Microsoft, Azure, Power_bi, Matplotlib, Tableau, Matlab, Java, gcp, cplusplus,Jupyter,Visio, Git, Other_skills)
freq_hardskills
```

```{r extracting other skills from description column}
freq_Otherskills<- skills_subset %>%
    mutate(Communication = grepl("communicat", description, ignore.case=TRUE)) %>%
    mutate(Collaborative = grepl("collaborat|group|team", description, ignore.case=TRUE)) %>%
    mutate(TimeManagement = grepl("manage", description, ignore.case=TRUE)) %>%
    mutate(Leadership = grepl("leader", description, ignore.case=TRUE)) %>%
    mutate(Remote = grepl("remote", description, ignore.case=TRUE)) %>%
    mutate(Machine_learning = grepl("machine learning", description, ignore.case=TRUE)) %>%          
    mutate(Experienced = grepl("experience", description, ignore.case=TRUE)) %>%
    mutate(Visualization = grepl("visualization", description, ignore.case=TRUE)) %>%
    mutate(Problem_solving = grepl("problem solving", description, ignore.case=TRUE)) %>%      
    mutate(Critical_analysis = grepl("critical", description, ignore.case=TRUE)) %>%
    mutate(Confidence = grepl("confiden", description, ignore.case=TRUE)) %>%
  select(title, Communication, Collaborative, TimeManagement, Leadership, Remote, Machine_learning, Experienced, Visualization, Problem_solving, Critical_analysis, Confidence)
freq_Otherskills
```

# Analysis:

```{r counting the frequency for every hard skill}
hardskills <- freq_hardskills %>%
  select(-1)%>%
  summarise_all(sum)%>%
  gather(skill, freq)%>%
  arrange(desc(freq))
hardskills
```

```{r counting the frequency for every other skill}
Otherskills <- freq_Otherskills %>%
  select(-1)%>%
  summarise_all(sum)%>%
  gather(skill, freq)%>%
  arrange(desc(freq))
Otherskills
```

```{r hard skill plot}
ggplot(hardskills,aes(x=reorder(skill, freq), y=freq)) + geom_bar(stat='identity',fill="orange") + xlab('') + ylab('Frequency') + labs(title='Data Science Hard Skills') + coord_flip() + theme_minimal()
```

```{r other skill plot}
ggplot(Otherskills,aes(x=reorder(skill, freq), y=freq)) + geom_bar(stat='identity',fill="blue") + xlab('') + ylab('Frequency') + labs(title='Data Science Other Required Skills') + coord_flip() + theme_minimal()
```

# Conclusion:
